# Generated by Django 5.0.6 on 2024-06-09 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_Turma', models.CharField(max_length=99, verbose_name='Turma')),
                ('Full_Name', models.CharField(max_length=99, verbose_name='Nome Professor')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id-Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_item', models.CharField(max_length=99, verbose_name='Atividade')),
                ('Full_Name', models.CharField(max_length=99, verbose_name='Nome Professor')),
                ('Nome_Turma', models.CharField(max_length=99, verbose_name='Nome Professor')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id-Professor')),
                ('id_lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turma', verbose_name='Id-Turma')),
            ],
        ),
    ]
