# Generated by Django 5.0.6 on 2024-06-09 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividades',
            old_name='Full_Name',
            new_name='First_Name',
        ),
    ]
