# Generated by Django 5.0.6 on 2024-06-09 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_full_name_atividades_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividades',
            name='First_Name',
        ),
    ]
