# Generated by Django 5.0.6 on 2024-06-09 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_atividades_first_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='Full_Name',
        ),
        migrations.AddField(
            model_name='atividades',
            name='First_Name',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='Nome Professor'),
        ),
        migrations.AddField(
            model_name='turma',
            name='First_Name',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='Nome Professor'),
        ),
        migrations.AlterField(
            model_name='atividades',
            name='Nome_Turma',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='Nome Professor'),
        ),
        migrations.AlterField(
            model_name='atividades',
            name='Nome_item',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='Atividade'),
        ),
        migrations.AlterField(
            model_name='atividades',
            name='id_lista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.turma', verbose_name='Id-Turma'),
        ),
        migrations.AlterField(
            model_name='atividades',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id-Professor'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='Nome_Turma',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id-Professor'),
        ),
    ]
